config/routes.rb
Rails.application.routes.draw do
  resources :disability_tools
  resources :users
  resources :gambles
  
#  resources :gambling, :path => "/gambles/:id/gambling"
  get 'users/new'

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: [:get]
  match '/help', to: 'static_pages#help', via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/update', to: 'static_pages#home', via: [:post]
  match '/update', to: 'static_pages#home', via: [:get]
  match '/content', to: 'static_pages#content', via: [:get]
  match '/gamble', to: 'static_pages#gamble', via: [:get]
  match '/gambles/:id/gambling(.:format)', to: 'gambles#gambling', via: [:get], as: 'gambling'
  match '/disability_tools/:id/generate(.:format)', to: 'disability_tools#generate', via: [:get], as: 'generation'
  match '/gambles/:id/gambling(.:format)', to: 'roll#send2', as: 'gambling_send', via: [:put]
  match '/test', to: 'disability_tools#new2', via: [:get] 
  match '/gambles/:id/gambling(.:format)', to: 'roll#send2', as: 'gambling_send_p', via: [:patch]
 match '/roll', to: 'roll#rolling', via: [:get]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def content
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
   <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
   <h1>About Us</h1>
     <p>
       This is the home page for the
       <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
       sample application.
     </p>

app/views/static_pages/content.html.erb
<% provide(:title, 'Content') %>
   <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
   <h1>Content</h1>
     <p>
       This is the home page for the
       <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
       sample application.
     </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
   <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
   <h1>Help</h1>
     <p>
       This is the home page for the
       <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
       sample application.
     </p>

app/views/static_pages/home.html.erb
<div class="hero-unit">
<h1>Statistics</h1>
<h2>
<table class="table">
<thread>
<tr>
<th class="center">First Name</th>
<th> other </th>
</tr>
</thread>
<tbody>
<tr>
<td> 
<%= getUsers(1)%></td>
<td>
<%= getEmail(1) %> </td>
</tr>
</tbody>
</table>
</h2>

<%= yieldHtmlTest %>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
<%= button_to "update", update_path, method: :post %> 
<%= link_to "gambles", gambles_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>