config/routes.rb
Rails.application.routes.draw do
  resources :disability_tools
  resources :users
  resources :gambles
  
#  resources :gambling, :path => "/gambles/:id/gambling"
  get 'users/new'

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: [:get]
  match '/help', to: 'static_pages#help', via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/update', to: 'static_pages#home', via: [:post]
  match '/update', to: 'static_pages#home', via: [:get]
  match '/content', to: 'static_pages#content', via: [:get]
  match '/gamble', to: 'static_pages#gamble', via: [:get]
  match '/gambles/:id/gambling(.:format)', to: 'gambles#gambling', via: [:get], as: 'gambling'
  match '/disability_tools/:id/generate(.:format)', to: 'disability_tools#generate', via: [:get], as: 'generation'
  match '/gambles/:id/gambling(.:format)', to: 'roll#send2', as: 'gambling_send', via: [:put]
  match '/test', to: 'disability_tools#new2', via: [:get] 
  match '/gambles/:id/gambling(.:format)', to: 'roll#send2', as: 'gambling_send_p', via: [:patch]
 match '/roll', to: 'roll#rolling', via: [:get]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gamble.rb
class Gamble < ApplicationRecord
end

app/controllers/gambles_controller.rb
class GamblesController < ApplicationController
  before_action :set_gamble, only: [:show, :edit, :update, :destroy]

# GET /gambles
 #GET /gambles.json
  def index
   @gambles = Gamble.all
  end

  # GET /gambles/1
  # GET /gambles/1.json
  def show
   
  end

# GET /gambles/new
  def new
    @gamble = Gamble.new
  end
  
  #GET /gambles/1/gambling
  
  def gambling
   @gamble2 = Gamble.find(params[:id])
  end
  
  # GET /gambles/1/edit
  def edit
  end
  
  def send2
    respond_to do |format|
      gamblingAmt = gamble_params
      gamblingInt = :amount.to_i
      gamblingInt = gamblingInt - gamblingAmt
      if @gamble.update(gamblingAmt)
        format.html { redirect_to @gamble, notice: 'Gamble was placed' }
      else
      end
     end
  end
  # POST /gambles
  # POST /gambles.json
  def create
    @gamble = Gamble.new(gamble_params)

    respond_to do |format|
      if @gamble.save
        format.html { redirect_to @gamble, notice: 'Gamble was successfully created.' }
        format.json { render :show, status: :created, location: @gamble }
      else
        format.html { render :new }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gambles/1
  # PATCH/PUT /gambles/1.json
  def update
    respond_to do |format|
      if @gamble.update(gamble_params)
        format.html { redirect_to @gamble, notice: 'Gamble was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamble }
      else
        format.html { render :edit }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gambles/1
  # DELETE /gambles/1.json
  def destroy
    @gamble.destroy
    respond_to do |format|
      format.html { redirect_to gambles_url, notice: 'Gamble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamble
      @gamble = Gamble.find(params[:id])
          
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def gamble_params
      params.require(:gamble).permit(:amount, :username)
    end
end

app/helpers/gambles_helper.rb
module GamblesHelper

def gambling
end

end

app/views/gambles/.#index.html.erb
unknown@here.7764

app/views/gambles/_form.html.erb
<%= form_for(gamble) do |f| %>
  <% if gamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamble.errors.count, "error") %> prohibited this gamble from being saved:</h2>

      <ul>
      <% gamble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <%= f.collection_select :username, Gamble.all, :id, :amount, prompt:true %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gambles/_form2.html.erb
<%= form_for(gamble, :url => gambling_send_path)  do |f| %>
  <% if gamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamble.errors.count, "error") %> prohibited this gamble from being saved:</h2>

      <ul>
      <% gamble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'bet' %>
    <%= f.number_field :bet %>
  </div>





  <div class="actions">
    
    <%= f.submit %>
    <%= :amount %>
    <%= :bet %>
  </div>
<% end %>

app/views/gambles/_form3.html.erb
<%= form_for(gamble) do |f| %>
  <% if gamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamble.errors.count, "error") %> prohibited this gamble from being saved:</h2>

      <ul>
      <% gamble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Account Balance: ' %>
    <%= gamble[:amount] %>
  </div>





<!--  <div class="actions">
    
    <%= f.submit %>
    
    
  </div> -->
<% end %>

app/views/gambles/copy2_ofindex.html.erb
<p id="notice"><%= notice %></p>

<h1>Gambles</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gambles.each do |gamble| %>
      <tr>
        <td><%= gamble.id %> </td>
        <td><%= gamble.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% @gambles.create( amount:24) %>
<br>

app/views/gambles/copyof_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gambles</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gambles.each do |gamble| %>
      <tr>
        <td><%= gamble.amount %></td>
<!--        <td><%= link_to 'Show', gamble %></td> 
        <td><%= link_to 'Edit', edit_gamble_path(gamble) %></td>
        <td><%= link_to 'Destroy', gamble, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Gamble', new_gamble_path %> -->

app/views/gambles/edit.html.erb
<h1>Editing Gamble</h1>

<%= render 'form', gamble: @gamble %>

<%= link_to 'Show', @gamble %> |
<%= link_to 'Back', gambles_path %>

app/views/gambles/gambling.html.erb
<h1>Editing Gamble</h1>

<%= render 'form2', gamble: @gamble2 %>
<%= render 'form3', gamble: @gamble2 %>
<%= link_to 'Show', @gamble %> |
<%= link_to 'Back', gambles_path %>

app/views/gambles/gambling2.html.erb
<h1>Editing Gamble</h1>

<%= render 'form', gamble: @gamble %>

<%= link_to 'Show', @gamble %> |
<%= link_to 'Back', gambles_path %>

app/views/gambles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gambles</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">Username</th>
      
    
    
	<th colspan="1">Amount</th>
	
    </tr>	
  </thead>

  <tbody>
    <% @gambles.each do |gamble| %>
      <tr>
        <td><%= link_to gamble.username, gambling_path(gamble)  %></td>
	<td><%= gamble.amount %></td>
        <td><%= link_to 'Show', gamble %></td> 
        <td><%= link_to 'Edit', edit_gamble_path(gamble) %></td>
        <td><%= link_to 'Destroy', gamble, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gamble', new_gamble_path %>

app/views/gambles/new.html.erb
<h1>New Gamble</h1>

<%= render 'form', gamble: @gamble %>

<%= link_to 'Back', gambles_path %>

app/views/gambles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @gamble.amount %>
</p>

<%= link_to 'Edit', edit_gamble_path(@gamble) %> |
<%= link_to 'Back', gambles_path %>