config/routes.rb
Rails.application.routes.draw do
  resources :disability_tools
  resources :users
  resources :gambles
  
#  resources :gambling, :path => "/gambles/:id/gambling"
  get 'users/new'

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: [:get]
  match '/help', to: 'static_pages#help', via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/update', to: 'static_pages#home', via: [:post]
  match '/update', to: 'static_pages#home', via: [:get]
  match '/content', to: 'static_pages#content', via: [:get]
  match '/gamble', to: 'static_pages#gamble', via: [:get]
  match '/gambles/:id/gambling(.:format)', to: 'gambles#gambling', via: [:get], as: 'gambling'
  match '/disability_tools/:id/generate(.:format)', to: 'disability_tools#generate', via: [:get], as: 'generation'
  match '/gambles/:id/gambling(.:format)', to: 'roll#send2', as: 'gambling_send', via: [:put]
  match '/test', to: 'disability_tools#new2', via: [:get] 
  match '/gambles/:id/gambling(.:format)', to: 'roll#send2', as: 'gambling_send_p', via: [:patch]
 match '/roll', to: 'roll#rolling', via: [:get]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">


<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Content", content_path  %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<%= link_to "sample app", '#', id: "logo" %>
<nav>
<ul class="nav nav-tabs">
<li role="presentation"><%= link_to "Home", root_path %></li>
<li role="presentation"><%= link_to "Help", help_path %></li>
<li role="presentation"><%= link_to "Sign in", '#' %></li>
</ul>
</nav>
</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
<%= stylesheet_link_tag "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>